### PR TITLE
Add TLS certificate generation with cfssl and documention.

### LINKED ISSUE #141: add TLS to workflow for vagrant workspace
Our vagrant env creates a space for testing and R&D on the CM formula. As part of that, we want to emulate production deployments where possible. This generally includes TLS, and in the context of our test env, self-signed certs with a bootstrapped CA. See https://www.nomadproject.io/guides/securing-nomad.html for info on using `cfssl` as one method to generate the certs needed.

### Requirements

* update the workflow with Vagrant to include generating the CA and TLS certs our vagrant vm will need
* nomad, consul, and vault will all be getting TLS certs, we don't need to cover them all in this task, but the goal is to get the framework in place. start with one and add others if needed, or support them all if it's easy
* don't get into configuring each of the services using the TLS certs, focus on the workflow to generate certs that are configured correctly for use with these services
* docs to describe what to do and how to control/configure it
* make targets or shell scripts with helper utilities

### PR DESCRIPTION
**Pull request by mcgirr**
Closes #141

### CODE REVIEW

**Comment by mcgirr** [comment]
I will rebase this on the current master and push to this MR.

**Comment by mcgirr** [comment]
That should be good to go now for review/merging!

**Comment by mcgirr** [comment]
I didn't make the change mentioned here: https://github.com/fpco/fpco-salt-formula/issues/141#issuecomment-427968372

**Comment by ketzacoatl** [comment]
good catch! I'd :+1: that change now before we move on.

**Comment by mcgirr** [comment]
Okay I'll make that change now

**Comment by mcgirr** [comment]
Okay that's ready and I made a small related update to the README as well.

**Pull request merged**
